#!/usr/bin/python3

import cv2
import time

esc = 27

def saveImage(image, index):
    filename = './{0}.jpg'.format('%02d' % index)
    cv2.imwrite(filename, image)
    print(filename)


face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
cap = cv2.VideoCapture(0)
cv2.namedWindow('video', cv2.WINDOW_NORMAL)
n = 1
idx = 0

while True:
    ret, frame = cap.read()
    frame = cv2.resize(frame, (320, 240))
    frame = cv2.flip(frame, 1)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 3)
    for (x, y, w, h) in faces:
        frame = cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)
        if n % 5 == 0:
            face_img = cv2.resize(gray[y: y + h, x: x + w], (200, 200))
            saveImage(face_img, idx)
            idx += 1
        n += 1
    cv2.imshow('video', frame)
    if cv2.waitKey(1) == esc:
        cv2.destroyAllWindows()
        break
